version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ladyjossy20
    networks:
      - default

networks:
  app-network:
    driver: bridge
