version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ladyjossy20
    volumes:
      - postgres-data:/var/lib/postgresql/data

